apiVersion: v1
kind: ConfigMap
metadata:
  name: tccatalog-api-config
  labels:
    app: tccatalog-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5001"
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__UserName: "guest"
  RabbitMq__VirtualHost: "/"
  RabbitMq__OrderPlacedQueue: "tccatalog.order.placed"
  RabbitMq__PaymentProcessedQueue: "tccatalog.payment.processed"
