apiVersion: apps/v1
kind: Deployment
metadata:
  name: tccatalog-api
  labels:
    app: tccatalog-api
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: tccatalog-api
  template:
    metadata:
      labels:
        app: tccatalog-api
    spec:
      containers:
        - name: tccatalog-api
          image: tccatalog-img:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              name: http
          envFrom:
            - configMapRef:
                name: tccatalog-api-config
            - secretRef:
                name: tccatalog-api-secret
          readinessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 5001
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
