apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  labels:
    app: catalog-api
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=CatalogDb;User Id=sa;Password=Jl130916;Encrypt=False;"
  Jwt__Secret: "VUo3co6md6zK+vubhB8OijmT80J022F5A7cW5yUOTuQ="
  RabbitMq__Password: "guest"
